name: CI

on:
  push:
    branches: [ main, fix-populate ]
  pull_request:
    branches: [ main ]

jobs:
  prepare-nds:
    name: Prepare NDS source (once, encrypted)
    runs-on: ubuntu-latest
    if: ${{ secrets.NDS_FORGEJO_TOKEN != '' }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Git for NDS Repository Access
      run: |
        git config --global url."https://oauth2:${{ secrets.NDS_FORGEJO_TOKEN }}@git.nds-association.org/".insteadOf "https://git.nds-association.org/"
    - name: Clone NDS SQLite DevKit
      run: |
        mkdir -p third_party
        git clone --depth 1 --branch SQLite-3.47.0 https://git.nds-association.org/NDS/sqlite-reference-engine.git third_party/nds-sqlite-devkit
    - name: Create password-protected archive
      env:
        NDS_FORGEJO_TOKEN: ${{ secrets.NDS_FORGEJO_TOKEN }}
      run: |
        KEY=$(python3 - <<'PY'
import os, hashlib
print(hashlib.sha256(os.environ['NDS_FORGEJO_TOKEN'].encode()).hexdigest())
PY
        )
        cd third_party
        zip -r -P "$KEY" nds-sqlite-devkit.zip nds-sqlite-devkit
    - name: Upload encrypted NDS source artifact
      uses: actions/upload-artifact@v4
      with:
        name: nds-sqlite-devkit-enc
        path: third_party/nds-sqlite-devkit.zip
        if-no-files-found: error
  build-public:
    name: Build with Public SQLite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake (Public SQLite)
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DSQLITE_BACKEND=PUBLIC \
          -DSQLITE_ENABLE_FTS5=ON \
          -DSQLITE_ENABLE_RTREE=ON \
          -DSQLITE_ENABLE_JSON1=ON \
          -DSQLITE_ENABLE_MATH=ON \
          -DSQLITE_ENABLE_COLUMN_METADATA=ON \
          examples/basic
      shell: bash
    
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
    
    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
      shell: bash

  build-nds:
    name: Build with NDS SQLite DevKit
    runs-on: ${{ matrix.os }}
    if: ${{ secrets.NDS_FORGEJO_TOKEN != '' }}
    needs: prepare-nds
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download encrypted NDS source
      uses: actions/download-artifact@v4
      with:
        name: nds-sqlite-devkit-enc
        path: third_party
    - name: Decrypt NDS source
      env:
        NDS_FORGEJO_TOKEN: ${{ secrets.NDS_FORGEJO_TOKEN }}
      shell: bash
      run: |
        KEY=$(python3 - <<'PY'
import os, hashlib
print(hashlib.sha256(os.environ['NDS_FORGEJO_TOKEN'].encode()).hexdigest())
PY
        )
        if [ "${{ runner.os }}" = "Windows" ]; then
          7z x -p"${KEY}" third_party/nds-sqlite-devkit.zip -othird_party
        else
          unzip -P "${KEY}" third_party/nds-sqlite-devkit.zip -d third_party
        fi
    
    - name: Configure CMake (NDS SQLite)
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DSQLITE_BACKEND=NDS \
          -DSQLITE_NDS_REPOSITORY_URL=https://git.nds-association.org/NDS/sqlite-reference-engine.git \
          -DSQLITE_NDS_TAG=SQLite-3.47.0 \
          -DFETCHCONTENT_SOURCE_DIR_NDS_SQLITE_DEVKIT=${{ github.workspace }}/third_party/nds-sqlite-devkit \
          -DFETCHCONTENT_UPDATES_DISCONNECTED=ON \
          -DSQLITE_ENABLE_FTS5=ON \
          -DSQLITE_ENABLE_RTREE=ON \
          -DSQLITE_ENABLE_JSON1=ON \
          -DSQLITE_ENABLE_MATH=ON \
          -DSQLITE_ENABLE_COLUMN_METADATA=ON \
          -DSQLITE_ENABLE_COMPRESSION=ON \
          examples/basic
      shell: bash
    
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
    
    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
      shell: bash

  examples:
    name: Test Examples
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Basic Example (Public)
      run: |
        cd examples/basic
        mkdir build && cd build
        cmake .. -DSQLITE_BACKEND=PUBLIC
        cmake --build .
        ./basic_example || true  # Run but don't fail if example exits with non-zero
    
    - name: Clean
      run: rm -rf examples/basic/build
    
    - name: Download encrypted NDS source
      if: ${{ secrets.NDS_FORGEJO_TOKEN != '' }}
      uses: actions/download-artifact@v4
      with:
        name: nds-sqlite-devkit-enc
        path: third_party
    - name: Decrypt NDS source
      if: ${{ secrets.NDS_FORGEJO_TOKEN != '' }}
      env:
        NDS_FORGEJO_TOKEN: ${{ secrets.NDS_FORGEJO_TOKEN }}
      run: |
        KEY=$(python3 - <<'PY'
import os, hashlib
print(hashlib.sha256(os.environ['NDS_FORGEJO_TOKEN'].encode()).hexdigest())
PY
        )
        unzip -P "${KEY}" third_party/nds-sqlite-devkit.zip -d third_party

    - name: Test Basic Example (NDS)
      if: ${{ secrets.NDS_FORGEJO_TOKEN != '' }}
      run: |
        cd examples/basic
        mkdir build && cd build
        cmake .. -DSQLITE_BACKEND=NDS \
          -DSQLITE_NDS_REPOSITORY_URL=https://git.nds-association.org/NDS/sqlite-reference-engine.git \
          -DSQLITE_NDS_TAG=SQLite-3.47.0 \
          -DFETCHCONTENT_SOURCE_DIR_NDS_SQLITE_DEVKIT=${{ github.workspace }}/third_party/nds-sqlite-devkit \
          -DFETCHCONTENT_UPDATES_DISCONNECTED=ON
        cmake --build .
        ./basic_example || true  # Run but don't fail if example exits with non-zero
